// Load test for POST /payments.
//
// Requires scripts/k6/data/accounts.json to exist (generated by
// scripts/seed_accounts.sh) with a JSON array of account ids to pay
// between.
//
// Usage (via ./scripts/run_load_test.sh, or directly):
//   k6 run -e BASE_URL=http://localhost:8080 -e VUS=50 -e STEADY_DURATION=30s scripts/k6/load_payments.js
import http from 'k6/http';
import { check, sleep } from 'k6';
import { Rate } from 'k6/metrics';
import { SharedArray } from 'k6/data';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
const CURRENCY = __ENV.CURRENCY || 'USD';
const MIN_AMOUNT = Number(__ENV.MIN_AMOUNT || 1);
const MAX_AMOUNT = Number(__ENV.MAX_AMOUNT || 100);
const VUS = Number(__ENV.VUS || 50);
const RAMP_UP = __ENV.RAMP_UP || '15s';
const STEADY_DURATION = __ENV.STEADY_DURATION || '30s';
const RAMP_DOWN = __ENV.RAMP_DOWN || '10s';

const accounts = new SharedArray('accounts', function () {
  const data = JSON.parse(open('./data/accounts.json'));
  if (!data.length) {
    throw new Error('accounts.json is empty - run scripts/seed_accounts.sh first');
  }
  return data;
});

const paymentSuccess = new Rate('payment_success');

export const options = {
  scenarios: {
    payments: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: RAMP_UP, target: VUS },
        { duration: STEADY_DURATION, target: VUS },
        { duration: RAMP_DOWN, target: 0 },
      ],
      gracefulRampDown: '5s',
    },
  },
  thresholds: {
    // 5xx / connection errors - the service itself misbehaving.
    http_req_failed: ['rate<0.01'],
    // 201s vs. business rejections (e.g. insufficient funds) - tune to taste.
    payment_success: ['rate>0.90'],
    http_req_duration: ['p(95)<500'],
  },
};

function randomAccountPair() {
  const from = accounts[Math.floor(Math.random() * accounts.length)];
  let to = accounts[Math.floor(Math.random() * accounts.length)];
  while (to === from && accounts.length > 1) {
    to = accounts[Math.floor(Math.random() * accounts.length)];
  }
  return [from, to];
}

export default function () {
  const [from, to] = randomAccountPair();
  const amount = Number((Math.random() * (MAX_AMOUNT - MIN_AMOUNT) + MIN_AMOUNT).toFixed(2));

  const payload = JSON.stringify({
    amount,
    currency: CURRENCY,
    from,
    to,
  });

  const res = http.post(`${BASE_URL}/payments`, payload, {
    headers: { 'Content-Type': 'application/json' },
    tags: { name: 'CreatePayment' },
  });

  paymentSuccess.add(res.status === 201);

  if (res.status >= 500) {
    console.error(`5xx from POST /payments: status=${res.status} body=${res.body}`);
  }

  check(res, {
    'no server error (5xx)': (r) => r.status < 500,
  });

  sleep(0.1);
}
