// Load test for POST /payments (v2: asynchronous acceptance).
//
// v2 no longer processes the payment synchronously - the handler only checks
// idempotency and enqueues the request (transactional outbox), then returns
// immediately. That means the k6 metrics below (http_req_duration,
// payment_accepted, ...) can only measure ACCEPTANCE latency and throughput,
// not the real business outcome (debited/credited/rejected):
//   - 202 Accepted: new idempotency key, persisted and enqueued.
//   - 200 OK: same idempotency key + same payload as a previous request -
//     replays the already-completed payment (won't normally happen here,
//     since every iteration uses a fresh key).
//   - 409 / 422: idempotency key reused incorrectly, or a previous attempt
//     with this key errored - see evolution/v2/README.md.
//
// Settlement (did the money actually move, and how long did it really take
// end to end) is now observable, but NOT via k6 metrics - it comes from the
// workers'/outbox_worker's own Prometheus instrumentation
// (payment_processing_duration_seconds, payments_outbox_pending). The
// teardown() below queries Prometheus directly after the run and prints
// those numbers, so a single `make test` run reports both halves of the
// picture. See evolution/v2/README.md's "SLO, reframed for v2".
//
// Requires scripts/k6/data/accounts.json to exist (generated by
// scripts/seed_accounts.sh) with a JSON array of account ids to pay
// between.
//
// Usage (via ./scripts/run_load_test.sh, or directly):
//   k6 run -e BASE_URL=http://localhost:8080 -e VUS=50 -e STEADY_DURATION=30s scripts/k6/load_payments.js
import http from 'k6/http';
import { check, sleep } from 'k6';
import { Rate } from 'k6/metrics';
import { SharedArray } from 'k6/data';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8080';
const PROMETHEUS_URL = __ENV.PROMETHEUS_URL || 'http://localhost:9090';
const CURRENCY = __ENV.CURRENCY || 'USD';
const MIN_AMOUNT = Number(__ENV.MIN_AMOUNT || 1);
const MAX_AMOUNT = Number(__ENV.MAX_AMOUNT || 100);
const VUS = Number(__ENV.VUS || 50);
const RAMP_UP = __ENV.RAMP_UP || '15s';
const STEADY_DURATION = __ENV.STEADY_DURATION || '30s';
const RAMP_DOWN = __ENV.RAMP_DOWN || '10s';
// How long to wait after the load stops before reading settlement metrics -
// needs to clear at least one outbox poll cycle (OUTBOX_POLL_INTERVAL,
// default 3s in .env) plus Kafka/worker processing time for the backlog
// built up during the run to have a real chance to drain.
const SETTLEMENT_WAIT = __ENV.SETTLEMENT_WAIT || '15s';

const accounts = new SharedArray('accounts', function () {
  const data = JSON.parse(open('./data/accounts.json'));
  if (!data.length) {
    throw new Error('accounts.json is empty - run scripts/seed_accounts.sh first');
  }
  return data;
});

const paymentAccepted = new Rate('payment_accepted');

export const options = {
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],
  scenarios: {
    payments: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: RAMP_UP, target: VUS },
        { duration: STEADY_DURATION, target: VUS },
        { duration: RAMP_DOWN, target: 0 },
      ],
      gracefulRampDown: '5s',
    },
  },
  thresholds: {
    // SLO (evolution/README.md): error rate < 0.1%.
    http_req_failed: ['rate<0.001'],
    // Every request here uses a fresh idempotency key, so a healthy system
    // should accept (202) essentially all of them - a drop here means the
    // accept path itself is rejecting/erroring, not a business outcome.
    payment_accepted: ['rate>0.99'],
    // Acceptance-latency target, NOT the old settlement-latency SLO - this
    // endpoint now only does an idempotency check + one DB insert, so it
    // should be far tighter than the 300ms/750ms synchronous SLO. Adjust
    // once a baseline run establishes what's actually achievable.
    http_req_duration: ['p(95)<50', 'p(99)<150'],
    // SLO: sustained throughput >= 1000 req/s of ACCEPTANCE. This is the
    // number v2 exists to hit after v1 topped out at 810 req/s of full
    // synchronous processing - see evolution/v1/throughput_ceiling.
    http_reqs: ['rate>=1000'],
  },
};

// Minimal UUIDv4 generator - doesn't need to be cryptographically random,
// just unique enough that every iteration gets its own idempotency key.
function uuidv4() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

function randomAccountPair() {
  const from = accounts[Math.floor(Math.random() * accounts.length)];
  let to = accounts[Math.floor(Math.random() * accounts.length)];
  while (to === from && accounts.length > 1) {
    to = accounts[Math.floor(Math.random() * accounts.length)];
  }
  return [from, to];
}

export default function () {
  const [from, to] = randomAccountPair();
  const amount = Number((Math.random() * (MAX_AMOUNT - MIN_AMOUNT) + MIN_AMOUNT).toFixed(2));

  const payload = JSON.stringify({
    idempotency_key: uuidv4(),
    amount,
    currency: CURRENCY,
    from,
    to,
  });

  const res = http.post(`${BASE_URL}/payments`, payload, {
    headers: { 'Content-Type': 'application/json' },
    tags: { name: 'CreatePayment' },
  });

  paymentAccepted.add(res.status === 202);

  if (res.status >= 500) {
    console.error(`5xx from POST /payments: status=${res.status} body=${res.body}`);
  }

  check(res, {
    'no server error (5xx)': (r) => r.status < 500,
    'accepted (202)': (r) => r.status === 202,
  });

  sleep(0.1);
}

// queryPrometheus returns the scalar value of an instant query, or null if
// the query failed or returned no series.
function queryPrometheus(query) {
  const res = http.get(`${PROMETHEUS_URL}/api/v1/query?query=${encodeURIComponent(query)}`);
  if (res.status !== 200) {
    console.error(`Prometheus query failed (status ${res.status}): ${query}`);
    return null;
  }

  const body = JSON.parse(res.body);
  const result = body && body.data && body.data.result;
  if (!result || result.length === 0) {
    return null;
  }
  return Number(result[0].value[1]);
}

// teardown runs once after the load stops. It reports the settlement-side
// numbers this script's own HTTP-level metrics can't see anymore: real
// accept-to-processed latency and whether the outbox backlog drained or is
// still growing.
export function teardown() {
  console.log(`Waiting ${SETTLEMENT_WAIT} for the outbox/Kafka pipeline to catch up before reading settlement metrics...`);
  sleep(Number(SETTLEMENT_WAIT.replace('s', '')));

  // Scoped to job="payment-service-workers": the observability package is
  // shared by all three processes, so web/outbox_worker also expose these
  // metric names (always at zero) - without the job filter their flat
  // zero series would get mixed into the aggregation.
  const p50 = queryPrometheus('histogram_quantile(0.50, sum(rate(payment_processing_duration_seconds_bucket{job="payment-service-workers"}[1m])) by (le))');
  const p95 = queryPrometheus('histogram_quantile(0.95, sum(rate(payment_processing_duration_seconds_bucket{job="payment-service-workers"}[1m])) by (le))');
  const p99 = queryPrometheus('histogram_quantile(0.99, sum(rate(payment_processing_duration_seconds_bucket{job="payment-service-workers"}[1m])) by (le))');
  const errorRate = queryPrometheus(
    'sum(rate(payment_processing_duration_seconds_count{job="payment-service-workers",outcome="error"}[1m])) / clamp_min(sum(rate(payment_processing_duration_seconds_count{job="payment-service-workers"}[1m])), 1e-9)'
  );
  const backlog = queryPrometheus('payments_outbox_pending{job="payment-service-outbox-worker"}');

  const fmtMs = (v) => (v === null ? 'n/a (no samples yet - is the workers/outbox_worker /metrics endpoint reachable?)' : `${(v * 1000).toFixed(1)}ms`);

  console.log('--- Settlement (accept -> processed), from workers/outbox_worker metrics ---');
  console.log(`  p50: ${fmtMs(p50)}`);
  console.log(`  p95: ${fmtMs(p95)}`);
  console.log(`  p99: ${fmtMs(p99)}`);
  console.log(`  error rate: ${errorRate === null ? 'n/a' : (errorRate * 100).toFixed(2) + '%'}`);
  console.log(`  outbox backlog (pending rows, right now): ${backlog === null ? 'n/a' : backlog}`);
  if (backlog !== null && backlog > 0) {
    console.log(
      '  NOTE: backlog is non-zero right after the wait above - check the "Outbox backlog" Grafana panel over the ' +
        'full test window to tell a still-draining backlog (fine) apart from one that grew the whole time (found the real ceiling).'
    );
  }
}
