FROM golang:1.27.0-alpine3.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o payment-service-workers ./cmd/workers/main.go

FROM alpine:3.24.1

WORKDIR /app

COPY --from=builder /app/payment-service-workers .

CMD ["./payment-service-workers"]